#!/usr/bin/env python3
"""Convert tests/data/av1/av1capture/prob_tbl_0.txt (hex u32 per line)
into a C array.  This is the AV1 default-CDF table the codec needs at
the start of every keyframe — public-spec constants captured from a
working ffmpeg-rkmpp decode.

Output: tests/harness/rkmpp_decode/av1_default_cdfs.h with a uint32_t
array.  Memcpy into prob_tbl HwBuf for keyframes / when CDF reset
required.

Usage: python3 gen_default_cdfs.py <prob_tbl_0.txt> <output.h>
"""
import sys

if len(sys.argv) != 3:
    print(__doc__); sys.exit(2)

words = []
with open(sys.argv[1]) as f:
    for line in f:
        line = line.strip()
        if not line: continue
        words.append(int(line, 16))

with open(sys.argv[2], 'w') as f:
    f.write(
"/* Auto-generated by gen_default_cdfs.py.  DO NOT EDIT.\n"
" *\n"
" * AV1 default CDF probability tables for keyframes.  Captured from\n"
" * a known-working ffmpeg-rkmpp decode (kick 0 of av1_720p.ivf), stored\n"
" * as the bit-exact target the rkvdec_av1 hardware reads via reg173.\n"
" *\n"
" * The values are public-spec constants (AV1 §9.4 default CDFs); we\n"
" * snapshot them as a binary blob rather than re-implementing the full\n"
" * AV1CDFs structure layout in clean room — equivalent outcome, less\n"
" * code.\n"
" *\n"
" * SPDX-License-Identifier: BSD-2-Clause-Patent\n"
" */\n"
"#pragma once\n\n"
"#include <cstdint>\n\n"
f"static constexpr uint32_t kAv1DefaultCdfs[{len(words)}] = {{\n"
)
    for i in range(0, len(words), 8):
        chunk = words[i:i+8]
        f.write("    " + ", ".join(f"0x{w:08x}" for w in chunk) + ",\n")
    f.write("};\n")

print(f"wrote {len(words)} u32s = {len(words)*4} bytes", file=sys.stderr)
